openapi: 3.1.0
info:
  version: 1.0.0
  title: <назва вашого додатку>
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    <опис вашого додатку>
tags:
  - name: Products
    description: Operations about products
  # теги, що ви будете використовувати
servers:
  - url: http://localhost:3000
paths:
  # тут будуть посилання на ендпоінти
  /products:
    get:
      $ref: ../swagger/paths/products/get.yaml
    post:
      $ref: ../swagger/paths/products/post.yaml
  /product/{id}:
    get:
      $ref: ../swagger/paths/products/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/products/{id}/patch.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
